package dao.mapper;

import java.util.List;
import model.news.TNews;
import model.news.TNewsExample;
import org.apache.ibatis.annotations.Param;

public interface TNewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    long countByExample(TNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    int deleteByExample(TNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    int insert(TNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    int insertSelective(TNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    List<TNews> selectByExampleWithBLOBs(TNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    List<TNews> selectByExample(TNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    TNews selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    int updateByExampleSelective(@Param("record") TNews record, @Param("example") TNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") TNews record, @Param("example") TNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    int updateByExample(@Param("record") TNews record, @Param("example") TNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    int updateByPrimaryKeySelective(TNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(TNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    int updateByPrimaryKey(TNews record);
}