package dao.mapper;

import java.util.List;
import model.newsarea.TNewsArea;
import model.newsarea.TNewsAreaExample;
import org.apache.ibatis.annotations.Param;

public interface TNewsAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_area
     *
     * @mbg.generated Thu Aug 24 22:05:48 CST 2017
     */
    long countByExample(TNewsAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_area
     *
     * @mbg.generated Thu Aug 24 22:05:48 CST 2017
     */
    int deleteByExample(TNewsAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_area
     *
     * @mbg.generated Thu Aug 24 22:05:48 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_area
     *
     * @mbg.generated Thu Aug 24 22:05:48 CST 2017
     */
    int insert(TNewsArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_area
     *
     * @mbg.generated Thu Aug 24 22:05:48 CST 2017
     */
    int insertSelective(TNewsArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_area
     *
     * @mbg.generated Thu Aug 24 22:05:48 CST 2017
     */
    List<TNewsArea> selectByExample(TNewsAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_area
     *
     * @mbg.generated Thu Aug 24 22:05:48 CST 2017
     */
    TNewsArea selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_area
     *
     * @mbg.generated Thu Aug 24 22:05:48 CST 2017
     */
    int updateByExampleSelective(@Param("record") TNewsArea record, @Param("example") TNewsAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_area
     *
     * @mbg.generated Thu Aug 24 22:05:48 CST 2017
     */
    int updateByExample(@Param("record") TNewsArea record, @Param("example") TNewsAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_area
     *
     * @mbg.generated Thu Aug 24 22:05:48 CST 2017
     */
    int updateByPrimaryKeySelective(TNewsArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_area
     *
     * @mbg.generated Thu Aug 24 22:05:48 CST 2017
     */
    int updateByPrimaryKey(TNewsArea record);
}