package model.news;

import java.util.Date;

public class TComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.id
     *
     * @mbg.generated Tue Aug 15 01:23:34 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.to_id
     *
     * @mbg.generated Tue Aug 15 01:23:34 CST 2017
     */
    private Integer toId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.to_type
     *
     * @mbg.generated Tue Aug 15 01:23:34 CST 2017
     */
    private Integer toType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.user_id
     *
     * @mbg.generated Tue Aug 15 01:23:34 CST 2017
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.user_name
     *
     * @mbg.generated Tue Aug 15 01:23:34 CST 2017
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.user_headpic
     *
     * @mbg.generated Tue Aug 15 01:23:34 CST 2017
     */
    private String userHeadpic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.createdtime
     *
     * @mbg.generated Tue Aug 15 01:23:34 CST 2017
     */
    private Date createdtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.content
     *
     * @mbg.generated Tue Aug 15 01:23:34 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.id
     *
     * @return the value of t_comment.id
     *
     * @mbg.generated Tue Aug 15 01:23:34 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.id
     *
     * @param id the value for t_comment.id
     *
     * @mbg.generated Tue Aug 15 01:23:34 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.to_id
     *
     * @return the value of t_comment.to_id
     *
     * @mbg.generated Tue Aug 15 01:23:34 CST 2017
     */
    public Integer getToId() {
        return toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.to_id
     *
     * @param toId the value for t_comment.to_id
     *
     * @mbg.generated Tue Aug 15 01:23:34 CST 2017
     */
    public void setToId(Integer toId) {
        this.toId = toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.to_type
     *
     * @return the value of t_comment.to_type
     *
     * @mbg.generated Tue Aug 15 01:23:34 CST 2017
     */
    public Integer getToType() {
        return toType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.to_type
     *
     * @param toType the value for t_comment.to_type
     *
     * @mbg.generated Tue Aug 15 01:23:34 CST 2017
     */
    public void setToType(Integer toType) {
        this.toType = toType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.user_id
     *
     * @return the value of t_comment.user_id
     *
     * @mbg.generated Tue Aug 15 01:23:34 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.user_id
     *
     * @param userId the value for t_comment.user_id
     *
     * @mbg.generated Tue Aug 15 01:23:34 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.user_name
     *
     * @return the value of t_comment.user_name
     *
     * @mbg.generated Tue Aug 15 01:23:34 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.user_name
     *
     * @param userName the value for t_comment.user_name
     *
     * @mbg.generated Tue Aug 15 01:23:34 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.user_headpic
     *
     * @return the value of t_comment.user_headpic
     *
     * @mbg.generated Tue Aug 15 01:23:34 CST 2017
     */
    public String getUserHeadpic() {
        return userHeadpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.user_headpic
     *
     * @param userHeadpic the value for t_comment.user_headpic
     *
     * @mbg.generated Tue Aug 15 01:23:34 CST 2017
     */
    public void setUserHeadpic(String userHeadpic) {
        this.userHeadpic = userHeadpic == null ? null : userHeadpic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.createdtime
     *
     * @return the value of t_comment.createdtime
     *
     * @mbg.generated Tue Aug 15 01:23:34 CST 2017
     */
    public Date getCreatedtime() {
        return createdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.createdtime
     *
     * @param createdtime the value for t_comment.createdtime
     *
     * @mbg.generated Tue Aug 15 01:23:34 CST 2017
     */
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.content
     *
     * @return the value of t_comment.content
     *
     * @mbg.generated Tue Aug 15 01:23:34 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.content
     *
     * @param content the value for t_comment.content
     *
     * @mbg.generated Tue Aug 15 01:23:34 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}