package model.news;

import java.util.Date;

public class TNews {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.id
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.title
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.digest
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    private String digest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.pic
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.source
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.tags
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    private String tags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.type
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.category_id
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.category_name
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    private String categoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.count_comment
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    private Integer countComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.count_like
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    private Integer countLike;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.count_browser
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    private Integer countBrowser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.publish_time
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    private Date publishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.status
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.city_id
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    private Integer cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.city_area_id
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    private String cityAreaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.city_name
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    private String cityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.source_docid
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    private String sourceDocid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.source_website
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    private String sourceWebsite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.source_url
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    private String sourceUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.check_time
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    private Date checkTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.createdtime
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    private Date createdtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.content
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.id
     *
     * @return the value of t_news.id
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.id
     *
     * @param id the value for t_news.id
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.title
     *
     * @return the value of t_news.title
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.title
     *
     * @param title the value for t_news.title
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.digest
     *
     * @return the value of t_news.digest
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public String getDigest() {
        return digest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.digest
     *
     * @param digest the value for t_news.digest
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public void setDigest(String digest) {
        this.digest = digest == null ? null : digest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.pic
     *
     * @return the value of t_news.pic
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.pic
     *
     * @param pic the value for t_news.pic
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.source
     *
     * @return the value of t_news.source
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.source
     *
     * @param source the value for t_news.source
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.tags
     *
     * @return the value of t_news.tags
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.tags
     *
     * @param tags the value for t_news.tags
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.type
     *
     * @return the value of t_news.type
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.type
     *
     * @param type the value for t_news.type
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.category_id
     *
     * @return the value of t_news.category_id
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.category_id
     *
     * @param categoryId the value for t_news.category_id
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.category_name
     *
     * @return the value of t_news.category_name
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.category_name
     *
     * @param categoryName the value for t_news.category_name
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.count_comment
     *
     * @return the value of t_news.count_comment
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public Integer getCountComment() {
        return countComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.count_comment
     *
     * @param countComment the value for t_news.count_comment
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public void setCountComment(Integer countComment) {
        this.countComment = countComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.count_like
     *
     * @return the value of t_news.count_like
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public Integer getCountLike() {
        return countLike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.count_like
     *
     * @param countLike the value for t_news.count_like
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public void setCountLike(Integer countLike) {
        this.countLike = countLike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.count_browser
     *
     * @return the value of t_news.count_browser
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public Integer getCountBrowser() {
        return countBrowser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.count_browser
     *
     * @param countBrowser the value for t_news.count_browser
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public void setCountBrowser(Integer countBrowser) {
        this.countBrowser = countBrowser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.publish_time
     *
     * @return the value of t_news.publish_time
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.publish_time
     *
     * @param publishTime the value for t_news.publish_time
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.status
     *
     * @return the value of t_news.status
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.status
     *
     * @param status the value for t_news.status
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.city_id
     *
     * @return the value of t_news.city_id
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.city_id
     *
     * @param cityId the value for t_news.city_id
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.city_area_id
     *
     * @return the value of t_news.city_area_id
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public String getCityAreaId() {
        return cityAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.city_area_id
     *
     * @param cityAreaId the value for t_news.city_area_id
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public void setCityAreaId(String cityAreaId) {
        this.cityAreaId = cityAreaId == null ? null : cityAreaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.city_name
     *
     * @return the value of t_news.city_name
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.city_name
     *
     * @param cityName the value for t_news.city_name
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.source_docid
     *
     * @return the value of t_news.source_docid
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public String getSourceDocid() {
        return sourceDocid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.source_docid
     *
     * @param sourceDocid the value for t_news.source_docid
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public void setSourceDocid(String sourceDocid) {
        this.sourceDocid = sourceDocid == null ? null : sourceDocid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.source_website
     *
     * @return the value of t_news.source_website
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public String getSourceWebsite() {
        return sourceWebsite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.source_website
     *
     * @param sourceWebsite the value for t_news.source_website
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public void setSourceWebsite(String sourceWebsite) {
        this.sourceWebsite = sourceWebsite == null ? null : sourceWebsite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.source_url
     *
     * @return the value of t_news.source_url
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public String getSourceUrl() {
        return sourceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.source_url
     *
     * @param sourceUrl the value for t_news.source_url
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public void setSourceUrl(String sourceUrl) {
        this.sourceUrl = sourceUrl == null ? null : sourceUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.check_time
     *
     * @return the value of t_news.check_time
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public Date getCheckTime() {
        return checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.check_time
     *
     * @param checkTime the value for t_news.check_time
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public void setCheckTime(Date checkTime) {
        this.checkTime = checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.createdtime
     *
     * @return the value of t_news.createdtime
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public Date getCreatedtime() {
        return createdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.createdtime
     *
     * @param createdtime the value for t_news.createdtime
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.content
     *
     * @return the value of t_news.content
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.content
     *
     * @param content the value for t_news.content
     *
     * @mbg.generated Tue Aug 22 16:44:49 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}