package model.newsarea;

import java.util.Date;

public class TNewsArea {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_area.id
     *
     * @mbg.generated Thu Aug 24 22:05:48 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_area.area_id
     *
     * @mbg.generated Thu Aug 24 22:05:48 CST 2017
     */
    private String areaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_area.name
     *
     * @mbg.generated Thu Aug 24 22:05:48 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_area.first_letter
     *
     * @mbg.generated Thu Aug 24 22:05:48 CST 2017
     */
    private String firstLetter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_area.parent_id
     *
     * @mbg.generated Thu Aug 24 22:05:48 CST 2017
     */
    private String parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_area.status
     *
     * @mbg.generated Thu Aug 24 22:05:48 CST 2017
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_area.createdtime
     *
     * @mbg.generated Thu Aug 24 22:05:48 CST 2017
     */
    private Date createdtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_area.id
     *
     * @return the value of t_news_area.id
     *
     * @mbg.generated Thu Aug 24 22:05:48 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_area.id
     *
     * @param id the value for t_news_area.id
     *
     * @mbg.generated Thu Aug 24 22:05:48 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_area.area_id
     *
     * @return the value of t_news_area.area_id
     *
     * @mbg.generated Thu Aug 24 22:05:48 CST 2017
     */
    public String getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_area.area_id
     *
     * @param areaId the value for t_news_area.area_id
     *
     * @mbg.generated Thu Aug 24 22:05:48 CST 2017
     */
    public void setAreaId(String areaId) {
        this.areaId = areaId == null ? null : areaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_area.name
     *
     * @return the value of t_news_area.name
     *
     * @mbg.generated Thu Aug 24 22:05:48 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_area.name
     *
     * @param name the value for t_news_area.name
     *
     * @mbg.generated Thu Aug 24 22:05:48 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_area.first_letter
     *
     * @return the value of t_news_area.first_letter
     *
     * @mbg.generated Thu Aug 24 22:05:48 CST 2017
     */
    public String getFirstLetter() {
        return firstLetter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_area.first_letter
     *
     * @param firstLetter the value for t_news_area.first_letter
     *
     * @mbg.generated Thu Aug 24 22:05:48 CST 2017
     */
    public void setFirstLetter(String firstLetter) {
        this.firstLetter = firstLetter == null ? null : firstLetter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_area.parent_id
     *
     * @return the value of t_news_area.parent_id
     *
     * @mbg.generated Thu Aug 24 22:05:48 CST 2017
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_area.parent_id
     *
     * @param parentId the value for t_news_area.parent_id
     *
     * @mbg.generated Thu Aug 24 22:05:48 CST 2017
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_area.status
     *
     * @return the value of t_news_area.status
     *
     * @mbg.generated Thu Aug 24 22:05:48 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_area.status
     *
     * @param status the value for t_news_area.status
     *
     * @mbg.generated Thu Aug 24 22:05:48 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_area.createdtime
     *
     * @return the value of t_news_area.createdtime
     *
     * @mbg.generated Thu Aug 24 22:05:48 CST 2017
     */
    public Date getCreatedtime() {
        return createdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_area.createdtime
     *
     * @param createdtime the value for t_news_area.createdtime
     *
     * @mbg.generated Thu Aug 24 22:05:48 CST 2017
     */
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }
}